-- =====================================================================
-- Load: Dim_Product (Phase 3.6)
--
-- Standalone SQL-only load path -- an alternative to running
-- generate_dim_product.py directly. Both produce identical results,
-- since data/generated/dim_product.csv IS the deterministic output of
-- that script (fixed seed -- see generate_dim_product.py ED-006).
--
-- Prerequisite: sql/schema.sql must already have been run once against
-- this database so the (empty) Dim_Product table exists.
-- Prerequisite: data/generated/dim_product.csv must already exist --
-- generated by python/generators/generate_dim_product.py.
--
-- Note: schema.sql's CHECK (list_price >= 0) and CHECK (unit_cost >= 0)
-- constraints apply to this load path too.
--
-- Run (from the project root, using the DuckDB CLI):
--   duckdb data/database/solstice_apparel.duckdb < sql/generation/load_dim_product.sql
-- =====================================================================

BEGIN TRANSACTION;

DELETE FROM Dim_Product;

COPY Dim_Product (
    product_key, product_id, product_name, category, subcategory,
    gender, size, color, collection_season, list_price, unit_cost, is_active
)
FROM 'data/generated/dim_product.csv' (HEADER, DELIMITER ',');

COMMIT;

SELECT COUNT(*) AS rows_loaded FROM Dim_Product;
