-- =====================================================================
-- Load: Dim_Campaign (Phase 3.5)
--
-- Standalone SQL-only load path -- an alternative to running
-- generate_dim_campaign.py directly. Both produce identical results,
-- since data/generated/dim_campaign.csv IS the deterministic output of
-- that script.
--
-- Prerequisite: sql/schema.sql must already have been run once against
-- this database so the (empty) Dim_Campaign table exists.
-- Prerequisite: data/generated/dim_campaign.csv must already exist --
-- generated by python/generators/generate_dim_campaign.py.
--
-- Note: schema.sql's CHECK (end_date >= start_date) constraint applies
-- to this load path too -- a malformed CSV loaded through this script
-- would be rejected by the database even without Python's validation.
--
-- Run (from the project root, using the DuckDB CLI):
--   duckdb data/database/solstice_apparel.duckdb < sql/generation/load_dim_campaign.sql
-- =====================================================================

BEGIN TRANSACTION;

DELETE FROM Dim_Campaign;

COPY Dim_Campaign (
    campaign_key, campaign_name, campaign_type, start_date, end_date,
    discount_depth, season, target_audience, is_active_flag
)
FROM 'data/generated/dim_campaign.csv' (HEADER, DELIMITER ',');

COMMIT;

SELECT COUNT(*) AS rows_loaded FROM Dim_Campaign;
