-- =====================================================================
-- Load: Dim_Customer (Phase 3.8)
--
-- Standalone SQL-only load path -- an alternative to running
-- generate_dim_customer.py directly. Both produce identical results,
-- since data/generated/dim_customer.csv IS the deterministic output of
-- that script (fixed seed -- see generate_dim_customer.py ED-006).
--
-- Prerequisite: sql/schema.sql must already have been run once against
-- this database so the (empty) Dim_Customer table exists.
-- Prerequisite: Dim_Marketing_Channel (6 rows) and Dim_Geography
-- (46 rows) must already be loaded -- Dim_Customer's FOREIGN KEY
-- REFERENCES constraints will reject the load otherwise, and
-- generate_dim_customer.py's own ED-007 checks would have already
-- caught this before the CSV was even written.
-- Prerequisite: data/generated/dim_customer.csv must already exist --
-- generated by python/generators/generate_dim_customer.py.
--
-- Run (from the project root, using the DuckDB CLI):
--   duckdb data/database/solstice_apparel.duckdb < sql/generation/load_dim_customer.sql
-- =====================================================================

BEGIN TRANSACTION;

DELETE FROM Dim_Customer;

COPY Dim_Customer (
    customer_key, customer_id, first_name, last_name, email,
    signup_date, birth_year, acquisition_channel_key, home_geography_key
)
FROM 'data/generated/dim_customer.csv' (HEADER, DELIMITER ',');

COMMIT;

SELECT COUNT(*) AS rows_loaded FROM Dim_Customer;
