-- =====================================================================
-- Load: Dim_Return_Reason (Phase 3.7)
--
-- Standalone SQL-only load path -- an alternative to running
-- generate_dim_return_reason.py directly. Both produce identical
-- results, since data/generated/dim_return_reason.csv IS the
-- deterministic output of that script.
--
-- Prerequisite: sql/schema.sql must already have been run once against
-- this database so the (empty) Dim_Return_Reason table exists.
-- Prerequisite: data/generated/dim_return_reason.csv must already exist
-- -- generated by python/generators/generate_dim_return_reason.py.
--
-- Run (from the project root, using the DuckDB CLI):
--   duckdb data/database/solstice_apparel.duckdb < sql/generation/load_dim_return_reason.sql
-- =====================================================================

BEGIN TRANSACTION;

DELETE FROM Dim_Return_Reason;

COPY Dim_Return_Reason (
    return_reason_key, reason_code, reason_description, is_controllable
)
FROM 'data/generated/dim_return_reason.csv' (HEADER, DELIMITER ',');

COMMIT;

SELECT COUNT(*) AS rows_loaded FROM Dim_Return_Reason;
