-- =====================================================================
-- Generation Load: Dim_Geography (Phase 3.2)
--
-- Standalone SQL-only load path -- an alternative to running
-- generate_dim_geography.py directly. Both produce identical results,
-- since data/generated/dim_geography.csv IS the deterministic output of
-- that script.
--
-- Wrapped in an explicit transaction for the same reason as the Python
-- loader: DELETE-then-INSERT is only safe to re-run repeatedly if a
-- failure partway through can't leave the table half-deleted. DuckDB
-- will roll back automatically if COPY fails before reaching COMMIT.
--
-- Prerequisite: sql/schema.sql already applied to this database, so the
-- empty Dim_Geography table exists.
-- Prerequisite: data/generated/dim_geography.csv already exists --
-- generated by python/generators/generate_dim_geography.py.
--
-- Run (from the project root, using the DuckDB CLI):
--   duckdb data/database/solstice_apparel.duckdb < sql/generation/load_dim_geography.sql
-- =====================================================================

BEGIN TRANSACTION;

DELETE FROM Dim_Geography;

COPY Dim_Geography (geography_key, city, state, region, country, postal_code)
FROM 'data/generated/dim_geography.csv' (HEADER, DELIMITER ',');

COMMIT;

SELECT COUNT(*) AS rows_loaded FROM Dim_Geography;
