-- =====================================================================
-- Load: Dim_Sales_Channel (Phase 3.4)
--
-- Standalone SQL-only load path -- an alternative to running
-- generate_dim_sales_channel.py directly. Both produce identical
-- results, since data/generated/dim_sales_channel.csv IS the
-- deterministic output of that script.
--
-- Prerequisite: sql/schema.sql must already have been run once against
-- this database so the (empty) Dim_Sales_Channel table exists.
-- Prerequisite: data/generated/dim_sales_channel.csv must already exist
-- -- generated by python/generators/generate_dim_sales_channel.py.
--
-- Run (from the project root, using the DuckDB CLI):
--   duckdb data/database/solstice_apparel.duckdb < sql/generation/load_dim_sales_channel.sql
-- =====================================================================

BEGIN TRANSACTION;

DELETE FROM Dim_Sales_Channel;

COPY Dim_Sales_Channel (
    sales_channel_key, channel_name, channel_type
)
FROM 'data/generated/dim_sales_channel.csv' (HEADER, DELIMITER ',');

COMMIT;

SELECT COUNT(*) AS rows_loaded FROM Dim_Sales_Channel;
